In [71]:
import pandas as pd
import numpy as np

normalized_data = pd.read_csv("data.csv")
federal_awards = pd.read_csv("FederalCoCData.csv", low_memory=False)

# Shrinking the dataframe to avoid empty rows
federal_awards = federal_awards[:31992]
federal_awards['Year'] = federal_awards['Year'].astype('Int64') 

#droping unnecessary columns
federal_awards = federal_awards.drop(columns=federal_awards.columns[[1, 2, 5]])

federal_awards[federal_awards.columns[1]] = federal_awards[federal_awards.columns[1]].astype(str)
federal_awards = federal_awards.rename(columns={'Unnamed: 3': 'CoC Number'})
federal_awards[['Org Name', 'Program Type']] = federal_awards[['Org Name', 'Program Type']].astype(str)
federal_awards['Award Amount'] = federal_awards['Award Amount'].astype('Int64')
federal_awards_Final = federal_awards.groupby(['CoC Number', 'Year'])['Award Amount'].sum().reset_index()

# federal_awards[federal_awards.columns[2]] = federal_awards[federal_awards.columns[2]].astype(str)
# federal_awards[federal_awards.columns[3]] = federal_awards[federal_awards.columns[3]].astype(str)

# federal_awards[federal_awards.columns[4]] = federal_awards[federal_awards.columns[4]].astype(int)

# Pivot federal_awards_Final so each year becomes a column
federal_awards_Final_pivot = federal_awards_Final.pivot(index='CoC Number', columns='Year', values='Award Amount')
federal_awards_Final_pivot.columns = [f'Award Amount - {int(year)}' for year in federal_awards_Final_pivot.columns]
federal_awards_Final_pivot = federal_awards_Final_pivot.reset_index()

# Join onto df on CoC Number
df_final = normalized_data.merge(federal_awards_Final_pivot, left_on='CoC Number', right_on='CoC Number', how='left')

# print(df['CoC Number'].head())
# print(federal_awards_Final['CoC Number'].head())
df_final = df_final.dropna()

df_final = df_final.sort_values('CoC Number')

pd.set_option('display.max_columns', None)
df_final

                                  NAME CoC Number  ttl_population 2024  \
373           Maricopa County, Arizona     AZ-502              4489967
372     Santa Clara County, California     CA-500              1869227
370         Alameda County, California     CA-502              1621569
369      Sacramento County, California     CA-503              1575171
368          Sonoma County, California     CA-504               478922
367    Contra Costa County, California     CA-505              1155874
365        Monterey County, California     CA-506               420883
356          Madera County, California     CA-514               154275
355          Fresno County, California     CA-514               999115
324     Los Angeles County, California     CA-600              9656697
323       San Diego County, California     CA-601              3198446
322          Orange County, California     CA-602              3126062
318  San Bernardino County, California     CA-609              2156389
317         Ventura County, California     CA-611               827795
300           Seminole County, Florida     FL-507               476338
299            Osceola County, Florida     FL-507               423945
298             Orange County, Florida     FL-507              1433107
272         Miami-Dade County, Florida     FL-600              2698120
271            Broward County, Florida     FL-601              1958597
261            Honolulu County, Hawaii     HI-501               969622
194         Hennepin County, Minnesota     MN-500              1245143
150           Essex County, New Jersey     NJ-504               843895
136               Clark County, Nevada     NV-500              2307841
92            Suffolk County, New York     NY-603              1502720
91             Nassau County, New York     NY-603              1370579
84               Franklin County, Ohio     OH-503              1303117
77                 Lane County, Oregon     OR-500               375499
76            Multnomah County, Oregon     OR-501               787098
70   Philadelphia County, Pennsylvania     PA-500              1535671
42                 Bexar County, Texas     TX-500              2027961
41                Travis County, Texas     TX-503              1304589
39                Dallas County, Texas     TX-600              2588967
38               Tarrant County, Texas     TX-601              2136011
31            Montgomery County, Texas     TX-700               680151
30                Harris County, Texas     TX-700              4786324
28              Salt Lake County, Utah     UT-500              1179694
13             King County, Washington     WA-500              2255985

     Percent of Homeless Dist 2024  Overall Homeless 2024  \
373                       1.000000                   9435
372                       1.000000                  10394
370                       1.000000                   9450
369                       1.000000                   6615
368                       1.000000                   2522
367                       1.000000                   2843
365                       0.862741                   3057
356                       0.133758                   4305
355                       0.866242                   4305
324                       1.000000                  71201
323                       1.000000                  10605
322                       1.000000                   7322
318                       1.000000                   4255
317                       1.000000                   2358
300                       0.204140                   2776
299                       0.181686                   2776
298                       0.614174                   2776
272                       1.000000                   3800
271                       1.000000                   2469
261                       1.000000                   4497
194                       1.000000                   3866
150                       1.000000                   2451
136                       1.000000                   7906
92                        0.522995                   4002
91                        0.477005                   4002
84                        1.000000                   2380
77                        1.000000                   3085
76                        1.000000                   7384
70                        1.000000                   5191
42                        1.000000                   3398
41                        0.976892                   2975
39                        1.000000                   3718
38                        1.000000                   2463
31                        0.123983                   3280
30                        0.872484                   3280
28                        1.000000                   2404
13                        1.000000                  16868

     Estimated Overall Homeless 2024  \
373                      9435.000000
372                     10394.000000
370                      9450.000000
369                      6615.000000
368                      2522.000000
367                      2843.000000
365                      2637.399109
356                       575.827669
355                      3729.172331
324                     71201.000000
323                     10605.000000
322                      7322.000000
318                      4255.000000
317                      2358.000000
300                       566.692361
299                       504.361174
298                      1704.946465
272                      3800.000000
271                      2469.000000
261                      4497.000000
194                      3866.000000
150                      2451.000000
136                      7906.000000
92                       2093.024583
91                       1908.975417
84                       2380.000000
77                       3085.000000
76                       7384.000000
70                       5191.000000
42                       3398.000000
41                       2906.252710
39                       3718.000000
38                       2463.000000
31                        406.662817
30                       2861.746877
28                       2404.000000
13                      16868.000000

     Estimated Overall Homeless 2024 Normalized  \
373                                    0.002101
372                                    0.005561
370                                    0.005828
369                                    0.004200
368                                    0.005266
367                                    0.002460
365                                    0.006266
356                                    0.003732
355                                    0.003732
324                                    0.007373
323                                    0.003316
322                                    0.002342
318                                    0.001973
317                                    0.002849
300                                    0.001190
299                                    0.001190
298                                    0.001190
272                                    0.001408
271                                    0.001261
261                                    0.004638
194                                    0.003105
150                                    0.002904
136                                    0.003426
92                                     0.001393
91                                     0.001393
84                                     0.001826
77                                     0.008216
76                                     0.009381
70                                     0.003380
42                                     0.001676
41                                     0.002228
39                                     0.001436
38                                     0.001153
31                                     0.000598
30                                     0.000598
28                                     0.002038
13                                     0.007477

     Overall Chronically Homeless 2024  \
373                               2135
372                               4137
370                               3832
369                               1574
368                                606
367                               1627
365                               1099
356                               1701
355                               1701
324                              29823
323                               3760
322                               2477
318                               1938
317                               1042
300                                719
299                                719
298                                719
272                               1110
271                                713
261                               1049
194                                643
150                                251
136                               2709
92                                 217
91                                 217
84                                 224
77                                1500
76                                2974
70                                1080
42                                 465
41                                1169
39                                 663
38                                 424
31                                 504
30                                 504
28                                 654
13                                8397

     Estimated Overall Chronically Homeless 2024  \
373                                  2135.000000
372                                  4137.000000
370                                  3832.000000
369                                  1574.000000
368                                   606.000000
367                                  1627.000000
365                                   948.152313
356                                   227.522152
355                                  1473.477848
324                                 29823.000000
323                                  3760.000000
322                                  2477.000000
318                                  1938.000000
317                                  1042.000000
300                                   146.776588
299                                   130.632451
298                                   441.590961
272                                  1110.000000
271                                   713.000000
261                                  1049.000000
194                                   643.000000
150                                   251.000000
136                                  2709.000000
92                                    113.489839
91                                    103.510161
84                                    224.000000
77                                   1500.000000
76                                   2974.000000
70                                   1080.000000
42                                    465.000000
41                                   1141.986359
39                                    663.000000
38                                    424.000000
31                                     62.487213
30                                    439.731837
28                                    654.000000
13                                   8397.000000

     Estimated Overall Chronically Homeless 2024 Normalized  \
373                                           0.226285
372                                           0.398018
370                                           0.405503
369                                           0.237944
368                                           0.240285
367                                           0.572283
365                                           0.359503
356                                           0.395122
355                                           0.395122
324                                           0.418856
323                                           0.354550
322                                           0.338296
318                                           0.455464
317                                           0.441900
300                                           0.259006
299                                           0.259006
298                                           0.259006
272                                           0.292105
271                                           0.288781
261                                           0.233267
194                                           0.166322
150                                           0.102407
136                                           0.342651
92                                            0.054223
91                                            0.054223
84                                            0.094118
77                                            0.486224
76                                            0.402763
70                                            0.208052
42                                            0.136845
41                                            0.392941
39                                            0.178322
38                                            0.172148
31                                            0.153659
30                                            0.153659
28                                            0.272047
13                                            0.497806

     Unsheltered Homeless 2024  Estimated Unsheltered Homeless 2024  \
373                       4076                          4076.000000
372                       7401                          7401.000000
370                       6343                          6343.000000
369                       3944                          3944.000000
368                       1577                          1577.000000
367                       1959                          1959.000000
365                       2379                          2052.460739
356                       2758                           368.904230
355                       2758                          2389.095770
324                      49509                         49509.000000
323                       6110                          6110.000000
322                       4173                          4173.000000
318                       3055                          3055.000000
317                       1431                          1431.000000
300                       1094                           223.329050
299                       1094                           198.764814
298                       1094                           671.906136
272                       1033                          1033.000000
271                       1624                          1624.000000
261                       2766                          2766.000000
194                        496                           496.000000
150                        284                           284.000000
136                       4202                          4202.000000
92                         209                           109.305881
91                         209                            99.694119
84                         514                           514.000000
77                        2096                          2096.000000
76                        3944                          3944.000000
70                         976                           976.000000
42                         914                           914.000000
41                        1266                          1236.744851
39                        1086                          1086.000000
38                         967                           967.000000
31                        1107                           137.248701
30                        1107                           965.839571
28                         413                           413.000000
13                        9810                          9810.000000

     Estimated Unsheltered Homeless 2024 Normalized  \
373                                        0.432008
372                                        0.712045
370                                        0.671217
369                                        0.596221
368                                        0.625297
367                                        0.689061
365                                        0.778214
356                                        0.640650
355                                        0.640650
324                                        0.695341
323                                        0.576143
322                                        0.569926
318                                        0.717979
317                                        0.606870
300                                        0.394092
299                                        0.394092
298                                        0.394092
272                                        0.271842
271                                        0.657756
261                                        0.615077
194                                        0.128298
150                                        0.115871
136                                        0.531495
92                                         0.052224
91                                         0.052224
84                                         0.215966
77                                         0.679417
76                                         0.534128
70                                         0.188018
42                                         0.268982
41                                         0.425546
39                                         0.292093
38                                         0.392611
31                                         0.337500
30                                         0.337500
28                                         0.171797
13                                         0.581575

     Sheltered Total Homeless 2024  Estimated Sheltered Total Homeless 2024  \
373                           5359                              5359.000000
372                           2993                              2993.000000
370                           3107                              3107.000000
369                           2671                              2671.000000
368                            945                               945.000000
367                            884                               884.000000
365                            678                               584.938370
356                           1547                               206.923439
355                           1547                              1340.076561
324                          21692                             21692.000000
323                           4495                              4495.000000
322                           3149                              3149.000000
318                           1200                              1200.000000
317                            927                               927.000000
300                           1682                               343.363311
299                           1682                               305.596360
298                           1682                              1033.040329
272                           2767                              2767.000000
271                            845                               845.000000
261                           1731                              1731.000000
194                           3370                              3370.000000
150                           2167                              2167.000000
136                           3704                              3704.000000

In [72]:
years = range(2010, 2025)

for year in years:
    award_col = f'Award Amount - {year}'
    homeless_col = f'Overall Homeless {year}'
    new_col = f'Award Per Unhoused Person - {year}'
    
    if award_col in df_final.columns and homeless_col in df_final.columns:
        df_final[new_col] = df_final[award_col] / df_final[homeless_col]
        # print(df_final[new_col])
    # else:
        # print(award_col, homeless_col, "DNE")

df_final.iloc[:, -20:]

,Award Amount - 2018,Award Amount - 2019,Award Amount - 2020,Award Amount - 2021,Award Amount - 2022,Award Amount - 2023,Award Per Unhoused Person - 2010,Award Per Unhoused Person - 2011,Award Per Unhoused Person - 2012,Award Per Unhoused Person - 2013,Award Per Unhoused Person - 2014,Award Per Unhoused Person - 2015,Award Per Unhoused Person - 2016,Award Per Unhoused Person - 2017,Award Per Unhoused Person - 2018,Award Per Unhoused Person - 2019,Award Per Unhoused Person - 2020,Award Per Unhoused Person - 2021,Award Per Unhoused Person - 2022,Award Per Unhoused Person - 2023
373,27746647,28412341,33039654,35726942,36265956,46542337,3422.074153,4108.899846,3887.640247,4577.178129,4458.640588,4773.989167,4457.815679,4618.868689,4405.628295,4295.787874,4453.383744,9788.203288,4017.943275,4827.041796
372,4741100,29506119,31678024,31236117,42667412,39486518,1532.289021,1669.809679,1479.968949,1450.66125,1518.004229,1519.078859,1427.588443,670.837841,653.584229,3039.987533,3298.076419,13575.018253,4254.827682,3987.32889
370,4739186,36369614,39150229,40087543,57331115,51466942,5205.447132,5538.498325,5671.499178,1604.355769,1482.652622,1521.131188,1275.578046,1006.066619,862.297307,4533.733982,4811.383679,15745.303614,5881.924182,5273.792602
369,20915190,23349292,27063723,29713497,30512102,33435948,5446.190929,6269.338805,5387.942034,4972.699764,7535.436096,7098.113953,7698.8236,5506.161801,5776.081193,4198.757777,4910.855199,15763.128382,3288.650787,3602.623424
368,3721504,3976410,4112614,4162516,4275968,4592448,730.935725,510.599868,619.84207,603.806776,696.424754,996.855667,1058.615279,1168.382363,1242.157543,1347.478821,1498.220036,5289.092757,1478.039405,2026.676081
367,12336831,15239701,16296852,16848402,22687043,19300140,3230.977891,3753.800414,3831.935038,4492.8485,4582.948731,4421.650419,5913.683237,6988.453018,5522.30573,6640.392593,7157.15942,20546.831707,7334.963789,8136.652614
365,1840661,1798544,1916620,2410304,2839225,7270850,803.796843,776.366432,728.988777,747.282234,716.407157,666.508956,651.09861,554.358799,557.945135,665.142012,714.357063,3555.020649,1181.042013,3287.002712
356,10733261,10662668,11198730,11509065,11693516,12738622,1416.275886,1203.661928,1276.385352,1882.108272,2963.963349,5073.965157,4783.10462,4658.170635,5006.185168,4251.46252,3075.729195,11520.585586,2773.604364,2835.215224
355,10733261,10662668,11198730,11509065,11693516,12738622,1416.275886,1203.661928,1276.385352,1882.108272,2963.963349,5073.965157,4783.10462,4658.170635,5006.185168,4251.46252,3075.729195,11520.585586,2773.604364,2835.215224
324,123220645,133611222,150913363,155356351,217847769,188900646,2532.453208,2546.856681,2464.768485,2295.43686,2668.903207,2362.839899,2366.508848,2062.699001,2466.63287,2375.015056,2368.903447,9019.236633,3345.790558,2648.634969
323,20069038,23876026,28814796,29250827,33008616,37066178,1197.049386,1669.943196,1549.1536,1488.477531,1694.05984,1800.537863,1921.431192,2007.966376,2340.139692,2946.929894,3772.557738,7060.30099,3917.006764,3611.280008
322,22481690,26143204,28994983,30789905,31453663,34301133,1828.548662,2347.482778,2110.43281,3857.592802,5038.814506,4815.768194,5025.175967,4759.509599,4537.172553,3810.962682,4155.199627,12613.643998,5500.815495,5669.60876
318,9517467,10622832,11662078,14825115,14808627,16961572,3679.76308,2642.681062,1743.216825,2814.546747,2845.896328,4099.68497,5168.428193,5260.449089,4493.610482,4074.734177,3731.86496,16381.342541,4443.032403,4043.282956
317,939303,2258458,2504049,3435065,3434832,3726301,632.316804,420.01547,403.242471,499.109916,592.630952,547.038814,609.877262,700.552951,718.12156,1353.180348,1401.258534,3619.668072,1527.950178,1526.546907
300,6586323,8740225,9530007,12004258,12658442,15058933,1272.598119,1262.360354,1699.597378,1197.558474,2665.807453,2922.868845,3697.020359,2984.153327,3208.145641,4348.370647,4748.384155,7774.778497,5884.910274,6669.14659
299,6586323,8740225,9530007,12004258,12658442,15058933,1272.598119,1262.360354,1699.597378,1197.558474,2665.807453,2922.868845,3697.020359,2984.153327,3208.145641,4348.370647,4748.384155,7774.778497,5884.910274,6669.14659
298,6586323,8740225,9530007,12004258,12658442,15058933,1272.598119,1262.360354,1699.597378,1197.558474,2665.807453,2922.868845,3697.020359,2984.153327,3208.145641,4348.370647,4748.384155,7774.778497,5884.910274,6669.14659
272,1288063,32867600,35333463,41016810,62774704,46393709,7654.06445,7712.477862,8003.466801,304.674382,278.72281,293.854287,288.095159,336.846815,366.343288,9466.474654,9925.130056,12722.335608,19161.997558,12686.275362
271,2238589,11362648,11813070,12121768,12137896,13541709,2970.327752,2513.851881,3178.576186,792.845196,806.285973,848.135755,963.455691,881.44,965.741588,4053.745273,5342.862958,4733.216712,5909.394352,5444.997587
261,9483399,10249234,10054187,14018071,14268617,15291984,2195.717094,2231.476618,4466.133241,555.157594,526.042657,420.8505,518.017611,682.906433,2109.766185,2320.406158,2260.383768,7560.987594,3616.886439,3796.421053
194,10851846,13516105,13733686,14366990,14523473,17941640,2835.734293,2891.703548,2708.237443,2325.806461,2440.066738,3038.910731,3181.002618,3350.912005,3601.674743,3975.325,4504.324697,6064.579992,5423.253547,5417.161836
150,4608395,6376138,6992985,6727557,6624627,7409741,4394.58683,4554.539535,3196.206117,1643.872418,2367.203641,1980.358385,2124.391231,1837.625488,2068.39991,2852.858166,3165.67904,3563.324682,3461.142633,4648.520075
136,7836705,13540428,14901170,15607116,31016994,17664815,657.914363,828.468699,899.173699,1248.926579,1122.231493,980.895326,1202.376611,1119.956394,1288.296071,2448.540325,2820.588681,3070.453669,5494.595926,2690.346482
92,12635476,12225380,14335319,15328548,15729385,17349161,1375.212457,1403.892617,3178.229235,2531.262568,2735.060804,2051.478632,2352.008333,2827.116078,3266.66908,3181.20739,3765.515892,5025.753443,5184.372116,4906.436934
91,12635476,12225380,14335319,15328548,15729385,17349161,1375.212457,1403.892617,3178.229235,2531.262568,2735.060804,2051.478632,2352.008333,2827.116078,3266.66908,3181.20739,3765.515892,5025.753443,5184.372116,4906.436934
84,13763737,15093005,19313798,19440623,20557392,24089917,6445.042538,6533.801834,6771.640865,6588.566532,6853.556382,6829.419524,6942.0058,7107.107037,7616.899281,7914.528055,9486.14833,14242.214652,10751.774059,10308.051776
77,3608512,3735118,4043991,4135613,4138087,6688364,901.185659,1101.352336,1329.967428,1575.810965,1561.515563,2281.880516,2327.939352,2264.165468,2198.971359,1725.227714,2518.051681,1784.899871,1436.835764,2368.40085
76,21355068,25584408,27951569,28599693,39380509,35085070,2439.337662,2467.521681,2952.705177,2252.986715,3094.193277,4038.216522,4804.620082,4830.874551,5313.527743,6372.206227,6698.195303,16067.243258,7532.614575,5571.711926
70,15341984,33751218,35598858,36383406,37499176,40128936,4653.801446,4693.740777,5256.780104,3298.644996,3278.287208,3007.98983,2727.577225,2812.004918,2650.653766,5885.129555,6318.576145,8457.32357,8353.57006,8492.896508
42,9729143,9935694,10329851,14208612,31709290,18032607,2034.179581,2164.538796,1959.210082,2409.951007,2436.662517,2786.182636,3111.994606,3345.052862,3173.236464,3459.503482,3523.141542,9478.727151,10587.409015,5715.564818
41,6780538,10383512,11011967,11033509,18737239,11924863,2092.394346,1995.246825,2430.519608,2704.329665,2824.37695,3104.418668,2659.802619,2915.344794,3158.145319,4604.661641,4394.240623,3735.107989,5935.14064,5023.109941
39,13642862,17036008,18595353,18960056,44872881,27254224,4013.018598,4299.047458,4544.170873,4262.726525,3857.700911,4230.932187,3388.73937,3515.903932,3310.570735,3754.078449,4159.10378,4148.808753,10175.256463,6421.824694
38,9500581,13604830,15423586,15890396,15909151,20429152,4722.42641,4985.535731,5550.98634,3469.444351,3519.503505,4588.982236,4285.572239,4573.599176,4714.928536,6708.496055,7254.74412,12223.381538,9555.045646,7359.204611
31,35209137,41760038,42588063,45243794,46204617,59600165,3457.785019,2824.330658,3538.794768,3164.257902,3770.051997,6243.517032,7420.34582,8403.919834,8498.464156,10604.377349,10716.674132,14848.636035,14790.210307,18226.350153
30,35209137,41760038,42588063,45243794,46204617,59600165,3457.785019,2824.330658,3538.794768,3164.257902,3770.051997,6243.517032,7420.34582,8403.919834,8498.464156,10604.377349,10716.674132,14848.636035,14790.210307,18226.350153
28,7449994,8013120,8843051,9778026,9848455,10825621,2323.310467,2357.30546,2305.664637,2501.079231,2617.034884,3203.346048,3627.165521,3381.981436,4129.708426,4345.509761,4516.369254,4225.594641,4700.933174,4712.939051
13,1358239,47515340,50009087,52776589,57878099,63855086,2492.481157,2543.982501,2681.513653,362.01197,359.678512,263.017585,209.935694,163.982135,112.139944,4242.819895,4255.730321,10182.633417,4329.600464,4513.045869

In [74]:
for col in df_final.columns:
    print(col)

NAME
CoC Number
ttl_population 2024
Percent of Homeless Dist 2024
Overall Homeless 2024
Estimated Overall Homeless 2024
Estimated Overall Homeless 2024 Normalized
Overall Chronically Homeless 2024
Estimated Overall Chronically Homeless 2024
Estimated Overall Chronically Homeless 2024 Normalized
Unsheltered Homeless 2024
Estimated Unsheltered Homeless 2024
Estimated Unsheltered Homeless 2024 Normalized
Sheltered Total Homeless 2024
Estimated Sheltered Total Homeless 2024
Estimated Sheltered Total Homeless 2024 Normalized
Sheltered ES Homeless 2024
Estimated Sheltered ES Homeless 2024
Estimated Sheltered ES Homeless 2024 Normalized
Sheltered TH Homeless 2024
Estimated Sheltered TH Homeless 2024
Estimated Sheltered TH Homeless 2024 Normalized
Sheltered SH Homeless 2024
Estimated Sheltered SH Homeless 2024
Estimated Sheltered SH Homeless 2024 Normalized
Total_Housing_Units 2024
People per Housing Unit 2024
Vacant_Units 2024
Vacancy Rate 2024
ttl_poverty 2024
ttl_poverty 2024 Normalized
ttl_extreme_poverty 2024
ttl_extreme_poverty 2024 Normalized
Median Rent 2024
Median Rent 2024 Normalized
ttl_population 2023
Percent of Homeless Dist 2023
Overall Homeless 2023
Estimated Overall Homeless 2023
Estimated Overall Homeless 2023 Normalized
Overall Chronically Homeless 2023
Estimated Overall Chronically Homeless 2023
Estimated Overall Chronically Homeless 2023 Normalized
Unsheltered Homeless 2023
Estimated Unsheltered Homeless 2023
Estimated Unsheltered Homeless 2023 Normalized
Sheltered Total Homeless 2023
Estimated Sheltered Total Homeless 2023
Estimated Sheltered Total Homeless 2023 Normalized
Sheltered ES Homeless 2023
Estimated Sheltered ES Homeless 2023
Estimated Sheltered ES Homeless 2023 Normalized
Sheltered TH Homeless 2023
Estimated Sheltered TH Homeless 2023
Estimated Sheltered TH Homeless 2023 Normalized
Sheltered SH Homeless 2023
Estimated Sheltered SH Homeless 2023
Estimated Sheltered SH Homeless 2023 Normalized
Total_Housing_Units 2023
People per Housing Unit 2023
Vacant_Units 2023
Vacancy Rate 2023
ttl_poverty 2023
ttl_poverty 2023 Normalized
ttl_extreme_poverty 2023
ttl_extreme_poverty 2023 Normalized
Median Rent 2023
Median Rent 2023 Normalized
ttl_population 2022
Percent of Homeless Dist 2022
Overall Homeless 2022
Estimated Overall Homeless 2022
Estimated Overall Homeless 2022 Normalized
Overall Chronically Homeless 2022
Estimated Overall Chronically Homeless 2022
Estimated Overall Chronically Homeless 2022 Normalized
Unsheltered Homeless 2022
Estimated Unsheltered Homeless 2022
Estimated Unsheltered Homeless 2022 Normalized
Sheltered Total Homeless 2022
Estimated Sheltered Total Homeless 2022
Estimated Sheltered Total Homeless 2022 Normalized
Sheltered ES Homeless 2022
Estimated Sheltered ES Homeless 2022
Estimated Sheltered ES Homeless 2022 Normalized
Sheltered TH Homeless 2022
Estimated Sheltered TH Homeless 2022
Estimated Sheltered TH Homeless 2022 Normalized
Sheltered SH Homeless 2022
Estimated Sheltered SH Homeless 2022
Estimated Sheltered SH Homeless 2022 Normalized
Total_Housing_Units 2022
People per Housing Unit 2022
Vacant_Units 2022
Vacancy Rate 2022
ttl_poverty 2022
ttl_poverty 2022 Normalized
ttl_extreme_poverty 2022
ttl_extreme_poverty 2022 Normalized
Median Rent 2022
Median Rent 2022 Normalized
ttl_population 2021
Percent of Homeless Dist 2021
Overall Homeless 2021
Estimated Overall Homeless 2021
Estimated Overall Homeless 2021 Normalized
Overall Chronically Homeless 2021
Estimated Overall Chronically Homeless 2021
Estimated Overall Chronically Homeless 2021 Normalized
Unsheltered Homeless 2021
Estimated Unsheltered Homeless 2021
Estimated Unsheltered Homeless 2021 Normalized
Sheltered Total Homeless 2021
Estimated Sheltered Total Homeless 2021
Estimated Sheltered Total Homeless 2021 Normalized
Sheltered ES Homeless 2021
Estimated Sheltered ES Homeless 2021
Estimated Sheltered ES Homeless 2021 Normalized
Sheltered TH Homeless 2021
Estimated Sheltered TH Homeless 2021
Estimated Sheltered TH Homeless 2021 Normalized
Sheltered SH Homeless 2021
Estimated Sheltered SH Homeless 2021
Estimated Sheltered SH Homeless 2021 Normalized
Total_Housing_Units 2021
People per Housing Unit 2021
Vacant_Units 2021
Vacancy Rate 2021
ttl_poverty 2021
ttl_poverty 2021 Normalized
ttl_extreme_poverty 2021
ttl_extreme_poverty 2021 Normalized
Median Rent 2021
Median Rent 2021 Normalized
ttl_population 2020
Percent of Homeless Dist 2020
Overall Homeless 2020
Estimated Overall Homeless 2020
Estimated Overall Homeless 2020 Normalized
Overall Chronically Homeless 2020
Estimated Overall Chronically Homeless 2020
Estimated Overall Chronically Homeless 2020 Normalized
Unsheltered Homeless 2020
Estimated Unsheltered Homeless 2020
Estimated Unsheltered Homeless 2020 Normalized
Sheltered Total Homeless 2020
Estimated Sheltered Total Homeless 2020
Estimated Sheltered Total Homeless 2020 Normalized
Sheltered ES Homeless 2020
Estimated Sheltered ES Homeless 2020
Estimated Sheltered ES Homeless 2020 Normalized
Sheltered TH Homeless 2020
Estimated Sheltered TH Homeless 2020
Estimated Sheltered TH Homeless 2020 Normalized
Sheltered SH Homeless 2020
Estimated Sheltered SH Homeless 2020
Estimated Sheltered SH Homeless 2020 Normalized
Total_Housing_Units 2020
People per Housing Unit 2020
Vacant_Units 2020
Vacancy Rate 2020
ttl_poverty 2020
ttl_poverty 2020 Normalized
ttl_extreme_poverty 2020
ttl_extreme_poverty 2020 Normalized
Median Rent 2020
Median Rent 2020 Normalized
ttl_population 2019
Percent of Homeless Dist 2019
Overall Homeless 2019
Estimated Overall Homeless 2019
Estimated Overall Homeless 2019 Normalized
Overall Chronically Homeless 2019
Estimated Overall Chronically Homeless 2019
Estimated Overall Chronically Homeless 2019 Normalized
Unsheltered Homeless 2019
Estimated Unsheltered Homeless 2019
Estimated Unsheltered Homeless 2019 Normalized
Sheltered Total Homeless 2019
Estimated Sheltered Total Homeless 2019
Estimated Sheltered Total Homeless 2019 Normalized
Sheltered ES Homeless 2019
Estimated Sheltered ES Homeless 2019
Estimated Sheltered ES Homeless 2019 Normalized
Sheltered TH Homeless 2019
Estimated Sheltered TH Homeless 2019
Estimated Sheltered TH Homeless 2019 Normalized
Sheltered SH Homeless 2019
Estimated Sheltered SH Homeless 2019
Estimated Sheltered SH Homeless 2019 Normalized
Total_Housing_Units 2019
People per Housing Unit 2019
Vacant_Units 2019
Vacancy Rate 2019
ttl_poverty 2019
ttl_poverty 2019 Normalized
ttl_extreme_poverty 2019
ttl_extreme_poverty 2019 Normalized
Median Rent 2019
Median Rent 2019 Normalized
ttl_population 2018
Percent of Homeless Dist 2018
Overall Homeless 2018
Estimated Overall Homeless 2018
Estimated Overall Homeless 2018 Normalized
Overall Chronically Homeless 2018
Estimated Overall Chronically Homeless 2018
Estimated Overall Chronically Homeless 2018 Normalized
Unsheltered Homeless 2018
Estimated Unsheltered Homeless 2018
Estimated Unsheltered Homeless 2018 Normalized
Sheltered Total Homeless 2018
Estimated Sheltered Total Homeless 2018
Estimated Sheltered Total Homeless 2018 Normalized
Sheltered ES Homeless 2018
Estimated Sheltered ES Homeless 2018
Estimated Sheltered ES Homeless 2018 Normalized
Sheltered TH Homeless 2018
Estimated Sheltered TH Homeless 2018
Estimated Sheltered TH Homeless 2018 Normalized
Sheltered SH Homeless 2018
Estimated Sheltered SH Homeless 2018
Estimated Sheltered SH Homeless 2018 Normalized
Total_Housing_Units 2018
People per Housing Unit 2018
Vacant_Units 2018
Vacancy Rate 2018
ttl_poverty 2018
ttl_poverty 2018 Normalized
ttl_extreme_poverty 2018
ttl_extreme_poverty 2018 Normalized
Median Rent 2018
Median Rent 2018 Normalized
ttl_population 2017
Percent of Homeless Dist 2017
Overall Homeless 2017
Estimated Overall Homeless 2017
Estimated Overall Homeless 2017 Normalized
Overall Chronically Homeless 2017
Estimated Overall Chronically Homeless 2017
Estimated Overall Chronically Homeless 2017 Normalized
Unsheltered Homeless 2017
Estimated Unsheltered Homeless 2017
Estimated Unsheltered Homeless 2017 Normalized
Sheltered Total Homeless 2017
Estimated Sheltered Total Homeless 2017
Estimated Sheltered Total Homeless 2017 Normalized
Sheltered ES Homeless 2017
Estimated Sheltered ES Homeless 2017
Estimated Sheltered ES Homeless 2017 Normalized
Sheltered TH Homeless 2017
Estimated Sheltered TH Homeless 2017
Estimated Sheltered TH Homeless 2017 Normalized
Sheltered SH Homeless 2017
Estimated Sheltered SH Homeless 2017
Estimated Sheltered SH Homeless 2017 Normalized
Total_Housing_Units 2017
People per Housing Unit 2017
Vacant_Units 2017
Vacancy Rate 2017
ttl_poverty 2017
ttl_poverty 2017 Normalized
ttl_extreme_poverty 2017
ttl_extreme_poverty 2017 Normalized
Median Rent 2017
Median Rent 2017 Normalized
ttl_population 2016
Percent of Homeless Dist 2016
Overall Homeless 2016
Estimated Overall Homeless 2016
Estimated Overall Homeless 2016 Normalized
Overall Chronically Homeless 2016
Estimated Overall Chronically Homeless 2016
Estimated Overall Chronically Homeless 2016 Normalized
Unsheltered Homeless 2016
Estimated Unsheltered Homeless 2016
Estimated Unsheltered Homeless 2016 Normalized
Sheltered Total Homeless 2016
Estimated Sheltered Total Homeless 2016
Estimated Sheltered Total Homeless 2016 Normalized
Sheltered ES Homeless 2016
Estimated Sheltered ES Homeless 2016
Estimated Sheltered ES Homeless 2016 Normalized
Sheltered TH Homeless 2016
Estimated Sheltered TH Homeless 2016
Estimated Sheltered TH Homeless 2016 Normalized
Sheltered SH Homeless 2016
Estimated Sheltered SH Homeless 2016
Estimated Sheltered SH Homeless 2016 Normalized
Total_Housing_Units 2016
People per Housing Unit 2016
Vacant_Units 2016
Vacancy Rate 2016
ttl_poverty 2016
ttl_poverty 2016 Normalized
ttl_extreme_poverty 2016
ttl_extreme_poverty 2016 Normalized
Median Rent 2016
Median Rent 2016 Normalized
ttl_population 2015
Percent of Homeless Dist 2015
Overall Homeless 2015
Estimated Overall Homeless 2015
Estimated Overall Homeless 2015 Normalized
Overall Chronically Homeless 2015
Estimated Overall Chronically Homeless 2015
Estimated Overall Chronically Homeless 2015 Normalized
Unsheltered Homeless 2015
Estimated Unsheltered Homeless 2015
Estimated Unsheltered Homeless 2015 Normalized
Sheltered Total Homeless 2015
Estimated Sheltered Total Homeless 2015
Estimated Sheltered Total Homeless 2015 Normalized
Sheltered ES Homeless 2015
Estimated Sheltered ES Homeless 2015
Estimated Sheltered ES Homeless 2015 Normalized
Sheltered TH Homeless 2015
Estimated Sheltered TH Homeless 2015
Estimated Sheltered TH Homeless 2015 Normalized
Sheltered SH Homeless 2015
Estimated Sheltered SH Homeless 2015
Estimated Sheltered SH Homeless 2015 Normalized
Total_Housing_Units 2015
People per Housing Unit 2015
Vacant_Units 2015
Vacancy Rate 2015
ttl_poverty 2015
ttl_poverty 2015 Normalized
ttl_extreme_poverty 2015
ttl_extreme_poverty 2015 Normalized
Median Rent 2015
Median Rent 2015 Normalized
ttl_population 2014
Percent of Homeless Dist 2014
Overall Homeless 2014
Estimated Overall Homeless 2014
Estimated Overall Homeless 2014 Normalized
Overall Chronically Homeless 2014
Estimated Overall Chronically Homeless 2014
Estimated Overall Chronically Homeless 2014 Normalized
Unsheltered Homeless 2014
Estimated Unsheltered Homeless 2014
Estimated Unsheltered Homeless 2014 Normalized
Sheltered Total Homeless 2014
Estimated Sheltered Total Homeless 2014
Estimated Sheltered Total Homeless 2014 Normalized
Sheltered ES Homeless 2014
Estimated Sheltered ES Homeless 2014
Estimated Sheltered ES Homeless 2014 Normalized
Sheltered TH Homeless 2014
Estimated Sheltered TH Homeless 2014
Estimated Sheltered TH Homeless 2014 Normalized
Sheltered SH Homeless 2014
Estimated Sheltered SH Homeless 2014
Estimated Sheltered SH Homeless 2014 Normalized
Total_Housing_Units 2014
People per Housing Unit 2014
Vacant_Units 2014
Vacancy Rate 2014
ttl_poverty 2014
ttl_poverty 2014 Normalized
ttl_extreme_poverty 2014
ttl_extreme_poverty 2014 Normalized
Median Rent 2014
Median Rent 2014 Normalized
ttl_population 2013
Percent of Homeless Dist 2013
Overall Homeless 2013
Estimated Overall Homeless 2013
Estimated Overall Homeless 2013 Normalized
Overall Chronically Homeless 2013
Estimated Overall Chronically Homeless 2013
Estimated Overall Chronically Homeless 2013 Normalized
Unsheltered Homeless 2013
Estimated Unsheltered Homeless 2013
Estimated Unsheltered Homeless 2013 Normalized
Sheltered Total Homeless 2013
Estimated Sheltered Total Homeless 2013
Estimated Sheltered Total Homeless 2013 Normalized
Sheltered ES Homeless 2013
Estimated Sheltered ES Homeless 2013
Estimated Sheltered ES Homeless 2013 Normalized
Sheltered TH Homeless 2013
Estimated Sheltered TH Homeless 2013
Estimated Sheltered TH Homeless 2013 Normalized
Sheltered SH Homeless 2013
Estimated Sheltered SH Homeless 2013
Estimated Sheltered SH Homeless 2013 Normalized
Total_Housing_Units 2013
People per Housing Unit 2013
Vacant_Units 2013
Vacancy Rate 2013
ttl_poverty 2013
ttl_poverty 2013 Normalized
ttl_extreme_poverty 2013
ttl_extreme_poverty 2013 Normalized
Median Rent 2013
Median Rent 2013 Normalized
ttl_population 2012
Percent of Homeless Dist 2012
Overall Homeless 2012
Estimated Overall Homeless 2012
Estimated Overall Homeless 2012 Normalized
Overall Chronically Homeless 2012
Estimated Overall Chronically Homeless 2012
Estimated Overall Chronically Homeless 2012 Normalized
Unsheltered Homeless 2012
Estimated Unsheltered Homeless 2012
Estimated Unsheltered Homeless 2012 Normalized
Sheltered Total Homeless 2012
Estimated Sheltered Total Homeless 2012
Estimated Sheltered Total Homeless 2012 Normalized
Sheltered ES Homeless 2012
Estimated Sheltered ES Homeless 2012
Estimated Sheltered ES Homeless 2012 Normalized
Sheltered TH Homeless 2012
Estimated Sheltered TH Homeless 2012
Estimated Sheltered TH Homeless 2012 Normalized
Sheltered SH Homeless 2012
Estimated Sheltered SH Homeless 2012
Estimated Sheltered SH Homeless 2012 Normalized
Total_Housing_Units 2012
People per Housing Unit 2012
Vacant_Units 2012
Vacancy Rate 2012
ttl_poverty 2012
ttl_poverty 2012 Normalized
ttl_extreme_poverty 2012
ttl_extreme_poverty 2012 Normalized
Median Rent 2012
Median Rent 2012 Normalized
ttl_population 2011
Percent of Homeless Dist 2011
Overall Homeless 2011
Estimated Overall Homeless 2011
Estimated Overall Homeless 2011 Normalized
Overall Chronically Homeless 2011
Estimated Overall Chronically Homeless 2011
Estimated Overall Chronically Homeless 2011 Normalized
Unsheltered Homeless 2011
Estimated Unsheltered Homeless 2011
Estimated Unsheltered Homeless 2011 Normalized
Sheltered Total Homeless 2011
Estimated Sheltered Total Homeless 2011
Estimated Sheltered Total Homeless 2011 Normalized
Sheltered ES Homeless 2011
Estimated Sheltered ES Homeless 2011
Estimated Sheltered ES Homeless 2011 Normalized
Sheltered TH Homeless 2011
Estimated Sheltered TH Homeless 2011
Estimated Sheltered TH Homeless 2011 Normalized
Sheltered SH Homeless 2011
Estimated Sheltered SH Homeless 2011
Estimated Sheltered SH Homeless 2011 Normalized
Total_Housing_Units 2011
People per Housing Unit 2011
Vacant_Units 2011
Vacancy Rate 2011
ttl_poverty 2011
ttl_poverty 2011 Normalized
ttl_extreme_poverty 2011
ttl_extreme_poverty 2011 Normalized
Median Rent 2011
Median Rent 2011 Normalized
ttl_population 2010
Percent of Homeless Dist 2010
Overall Homeless 2010
Estimated Overall Homeless 2010
Estimated Overall Homeless 2010 Normalized
Overall Chronically Homeless 2010
Estimated Overall Chronically Homeless 2010
Estimated Overall Chronically Homeless 2010 Normalized
Unsheltered Homeless 2010
Estimated Unsheltered Homeless 2010
Estimated Unsheltered Homeless 2010 Normalized
Sheltered Total Homeless 2010
Estimated Sheltered Total Homeless 2010
Estimated Sheltered Total Homeless 2010 Normalized
Sheltered ES Homeless 2010
Estimated Sheltered ES Homeless 2010
Estimated Sheltered ES Homeless 2010 Normalized
Sheltered TH Homeless 2010
Estimated Sheltered TH Homeless 2010
Estimated Sheltered TH Homeless 2010 Normalized
Sheltered SH Homeless 2010
Estimated Sheltered SH Homeless 2010
Estimated Sheltered SH Homeless 2010 Normalized
Total_Housing_Units 2010
People per Housing Unit 2010
Vacant_Units 2010
Vacancy Rate 2010
ttl_poverty 2010
ttl_poverty 2010 Normalized
ttl_extreme_poverty 2010
ttl_extreme_poverty 2010 Normalized
Median Rent 2010
Median Rent 2010 Normalized
Award Amount - 2007
Award Amount - 2008
Award Amount - 2009
Award Amount - 2010
Award Amount - 2011
Award Amount - 2012
Award Amount - 2013
Award Amount - 2014
Award Amount - 2015
Award Amount - 2016
Award Amount - 2017
Award Amount - 2018
Award Amount - 2019
Award Amount - 2020
Award Amount - 2021
Award Amount - 2022
Award Amount - 2023
Award Per Unhoused Person - 2010
Award Per Unhoused Person - 2011
Award Per Unhoused Person - 2012
Award Per Unhoused Person - 2013
Award Per Unhoused Person - 2014
Award Per Unhoused Person - 2015
Award Per Unhoused Person - 2016
Award Per Unhoused Person - 2017
Award Per Unhoused Person - 2018
Award Per Unhoused Person - 2019
Award Per Unhoused Person - 2020
Award Per Unhoused Person - 2021
Award Per Unhoused Person - 2022
Award Per Unhoused Person - 2023

In [79]:
years = range(2010, 2025)

# Non-relative score: weighted sum of normalized chronic, overall, and unsheltered homeless
for year in years:
    chronic_col = f'Estimated Overall Chronically Homeless {year} Normalized'
    overall_col = f'Estimated Overall Homeless {year} Normalized'
    unsheltered_col = f'Estimated Unsheltered Homeless {year} Normalized'
    
    if all(c in df_final.columns for c in [chronic_col, overall_col, unsheltered_col]):
        df_final[f'Non-Relative Score {year}'] = (
            0.6 * df_final[chronic_col] +
            0.3 * df_final[overall_col] +
            0.1 * df_final[unsheltered_col]
        )

# Relative score: (current / prior) * current non-relative score
# 2010 base case: relative = non-relative
df_final['Relative Score 2010'] = df_final['Non-Relative Score 2010']

for year in range(2011, 2025):
    current_col = f'Non-Relative Score {year}'
    prior_col = f'Non-Relative Score {year - 1}'
    
    if all(c in df_final.columns for c in [current_col, prior_col]):
        df_final[f'Relative Score {year}'] = (
            df_final[current_col] / df_final[prior_col]
        ) * df_final[current_col]

df_final.iloc[:, -50:]

,Award Amount - 2018,Award Amount - 2019,Award Amount - 2020,Award Amount - 2021,Award Amount - 2022,Award Amount - 2023,Award Per Unhoused Person - 2010,Award Per Unhoused Person - 2011,Award Per Unhoused Person - 2012,Award Per Unhoused Person - 2013,Award Per Unhoused Person - 2014,Award Per Unhoused Person - 2015,Award Per Unhoused Person - 2016,Award Per Unhoused Person - 2017,Award Per Unhoused Person - 2018,Award Per Unhoused Person - 2019,Award Per Unhoused Person - 2020,Award Per Unhoused Person - 2021,Award Per Unhoused Person - 2022,Award Per Unhoused Person - 2023,Non-Relative Score 2010,Non-Relative Score 2011,Non-Relative Score 2012,Non-Relative Score 2013,Non-Relative Score 2014,Non-Relative Score 2015,Non-Relative Score 2016,Non-Relative Score 2017,Non-Relative Score 2018,Non-Relative Score 2019,Non-Relative Score 2020,Non-Relative Score 2021,Non-Relative Score 2022,Non-Relative Score 2023,Non-Relative Score 2024,Relative Score 2010,Relative Score 2011,Relative Score 2012,Relative Score 2013,Relative Score 2014,Relative Score 2015,Relative Score 2016,Relative Score 2017,Relative Score 2018,Relative Score 2019,Relative Score 2020,Relative Score 2021,Relative Score 2022,Relative Score 2023,Relative Score 2024
373,27746647,28412341,33039654,35726942,36265956,46542337,3422.074153,4108.899846,3887.640247,4577.178129,4458.640588,4773.989167,4457.815679,4618.868689,4405.628295,4295.787874,4453.383744,9788.203288,4017.943275,4827.041796,0.117815,0.142817,0.115841,0.078147,0.059107,0.074462,0.107685,0.137663,0.134810,0.135935,0.136365,0.096912,0.141889,0.170162,0.179602,0.117815,0.173124,0.093960,0.052719,0.044706,0.093807,0.155729,0.175986,0.132017,0.137069,0.136797,0.068873,0.207742,0.204069,0.189566
372,4741100,29506119,31678024,31236117,42667412,39486518,1532.289021,1669.809679,1479.968949,1450.66125,1518.004229,1519.078859,1427.588443,670.837841,653.584229,3039.987533,3298.076419,13575.018253,4254.827682,3987.32889,0.263735,0.291256,0.300521,0.273619,0.277239,0.273628,0.269341,0.245025,0.253177,0.235906,0.241792,0.268420,0.248264,0.308555,0.311684,0.263735,0.321648,0.310080,0.249125,0.280907,0.270065,0.265120,0.222905,0.261600,0.219813,0.247825,0.297981,0.229622,0.383487,0.314844
370,4739186,36369614,39150229,40087543,57331115,51466942,5205.447132,5538.498325,5671.499178,1604.355769,1482.652622,1521.131188,1275.578046,1006.066619,862.297307,4533.733982,4811.383679,15745.303614,5881.924182,5273.792602,0.187906,0.228120,0.206731,0.203968,0.209194,0.171497,0.167616,0.251631,0.261482,0.247400,0.258762,0.224344,0.242916,0.247371,0.312172,0.187906,0.276941,0.187348,0.201241,0.214554,0.140593,0.163823,0.377759,0.271718,0.234076,0.270646,0.194504,0.263026,0.251907,0.393948
369,20915190,23349292,27063723,29713497,30512102,33435948,5446.190929,6269.338805,5387.942034,4972.699764,7535.436096,7098.113953,7698.8236,5506.161801,5776.081193,4198.757777,4910.855199,15763.128382,3288.650787,3602.623424,0.139068,0.129840,0.133356,0.135528,0.135998,0.149480,0.168034,0.241073,0.254913,0.248295,0.259881,0.202169,0.352593,0.354219,0.203649,0.139068,0.121224,0.136968,0.137735,0.136471,0.164299,0.188891,0.345860,0.269548,0.241849,0.272008,0.157273,0.614939,0.355854,0.117082
368,3721504,3976410,4112614,4162516,4275968,4592448,730.935725,510.599868,619.84207,603.806776,696.424754,996.855667,1058.615279,1168.382363,1242.157543,1347.478821,1498.220036,5289.092757,1478.039405,2026.676081,0.252382,0.211457,0.216030,0.243725,0.257420,0.204420,0.221596,0.193431,0.215803,0.205356,0.186526,0.187271,0.224339,0.204023,0.208280,0.252382,0.177168,0.220703,0.274969,0.271886,0.162332,0.240216,0.168846,0.240761,0.195414,0.169424,0.188019,0.268744,0.185547,0.212627
367,12336831,15239701,16296852,16848402,22687043,19300140,3230.977891,3753.800414,3831.935038,4492.8485,4582.948731,4421.650419,5913.683237,6988.453018,5522.30573,6640.392593,7157.15942,20546.831707,7334.963789,8136.652614,0.273067,0.246979,0.252489,0.293218,0.298173,0.249355,0.197813,0.180706,0.218457,0.203266,0.253740,0.289970,0.380080,0.472498,0.413014,0.273067,0.223383,0.258122,0.340518,0.303211,0.208529,0.156926,0.165079,0.264093,0.189131,0.316748,0.331372,0.498194,0.587386,0.361019
365,1840661,1798544,1916620,2410304,2839225,7270850,803.796843,776.366432,728.988777,747.282234,716.407157,666.508956,651.09861,554.358799,557.945135,665.142012,714.357063,3555.020649,1181.042013,3287.002712,0.232060,0.256556,0.257775,0.287352,0.296991,0.194368,0.202692,0.237742,0.249613,0.217827,0.211005,0.139357,0.255021,0.241649,0.295403,0.232060,0.283639,0.258999,0.320323,0.306954,0.127206,0.211371,0.278854,0.262076,0.190089,0.204397,0.092038,0.466684,0.228979,0.361114
356,10733261,10662668,11198730,11509065,11693516,12738622,1416.275886,1203.661928,1276.385352,1882.108272,2963.963349,5073.965157,4783.10462,4658.170635,5006.185168,4251.46252,3075.729195,11520.585586,2773.604364,2835.215224,0.181507,0.173557,0.196424,0.233874,0.188416,0.197399,0.250491,0.282345,0.225627,0.250156,0.180898,0.143808,0.190055,0.262872,0.302258,0.181507,0.165955,0.222303,0.278464,0.151793,0.206810,0.317862,0.318249,0.180303,0.277353,0.130814,0.114323,0.251176,0.363587,0.347545
355,10733261,10662668,11198730,11509065,11693516,12738622,1416.275886,1203.661928,1276.385352,1882.108272,2963.963349,5073.965157,4783.10462,4658.170635,5006.185168,4251.46252,3075.729195,11520.585586,2773.604364,2835.215224,0.181507,0.173557,0.196424,0.233874,0.188416,0.197399,0.250491,0.282345,0.225627,0.250156,0.180898,0.143808,0.190055,0.262872,0.302258,0.181507,0.165955,0.222303,0.278464,0.151793,0.206810,0.317862,0.318249,0.180303,0.277353,0.130814,0.114323,0.251176,0.363587,0.347545
324,123220645,133611222,150913363,155356351,217847769,188900646,2532.453208,2546.856681,2464.768485,2295.43686,2668.903207,2362.839899,2366.508848,2062.699001,2466.63287,2375.015056,2368.903447,9019.236633,3345.790558,2648.634969,0.197039,0.219368,0.207994,0.211662,0.221683,0.278089,0.260344,0.260846,0.236158,0.242913,0.304860,0.147345,0.321126,0.344682,0.323060,0.197039,0.244226,0.197210,0.215394,0.232178,0.348848,0.243732,0.261348,0.213806,0.249861,0.382604,0.071215,0.699864,0.369967,0.302793
323,20069038,23876026,28814796,29250827,33008616,37066178,1197.049386,1669.943196,1549.1536,1488.477531,1694.05984,1800.537863,1921.431192,2007.966376,2340.139692,2946.929894,3772.557738,7060.30099,3917.006764,3611.280008,0.145067,0.208047,0.218592,0.223419,0.135492,0.164298,0.155878,0.204756,0.210873,0.182781,0.172021,0.116824,0.150190,0.256878,0.271339,0.145067,0.298368,0.229672,0.228352,0.082169,0.199228,0.147890,0.268959,0.217173,0.158431,0.161896,0.079338,0.193085,0.439354,0.286614
322,22481690,26143204,28994983,30789905,31453663,34301133,1828.548662,2347.482778,2110.43281,3857.592802,5038.814506,4815.768194,5025.175967,4759.509599,4537.172553,3810.962682,4155.199627,12613.643998,5500.815495,5669.60876,0.341917,0.206656,0.206296,0.156904,0.171574,0.128040,0.150847,0.166195,0.181706,0.282479,0.299049,0.113301,0.312456,0.301721,0.260673,0.341917,0.124904,0.205937,0.119337,0.187617,0.095551,0.177717,0.183106,0.198665,0.439140,0.316590,0.042927,0.861678,0.291355,0.225209
318,9517467,10622832,11662078,14825115,14808627,16961572,3679.76308,2642.681062,1743.216825,2814.546747,2845.896328,4099.68497,5168.428193,5260.449089,4493.610482,4074.734177,3731.86496,16381.342541,4443.032403,4043.282956,0.169307,0.111287,0.116968,0.208145,0.197016,0.218790,0.192168,0.205255,0.188267,0.250547,0.222845,0.037918,0.272865,0.277059,0.345668,0.169307,0.073150,0.122939,0.370394,0.186483,0.242970,0.168785,0.219234,0.172684,0.333429,0.198206,0.006452,1.963597,0.281317,0.431268
317,939303,2258458,2504049,3435065,3434832,3726301,632.316804,420.01547,403.242471,499.109916,592.630952,547.038814,609.877262,700.552951,718.12156,1353.180348,1401.258534,3619.668072,1527.950178,1526.546907,0.331964,0.279888,0.219768,0.350435,0.249119,0.289503,0.204628,0.258573,0.192365,0.192451,0.215473,0.210247,0.231417,0.341114,0.326682,0.331964,0.235982,0.172561,0.558794,0.177095,0.336434,0.144637,0.326738,0.143110,0.192536,0.241249,0.205148,0.254719,0.502810,0.312860
300,6586323,8740225,9530007,12004258,12658442,15058933,1272.598119,1262.360354,1699.597378,1197.558474,2665.807453,2922.868845,3697.020359,2984.153327,3208.145641,4348.370647,4748.384155,7774.778497,5884.910274,6669.14659,0.289211,0.367649,0.208826,0.263822,0.045434,0.074382,0.046302,0.072824,0.097325,0.159687,0.169336,0.061608,0.132505,0.149590,0.195170,0.289211,0.467360,0.118614,0.333301,0.007824,0.121773,0.028823,0.114538,0.130070,0.262007,0.179569,0.022414,0.284989,0.168877,0.254638
299,6586323,8740225,9530007,12004258,12658442,15058933,1272.598119,1262.360354,1699.597378,1197.558474,2665.807453,2922.868845,3697.020359,2984.153327,3208.145641,4348.370647,4748.384155,7774.778497,5884.910274,6669.14659,0.289211,0.367649,0.208826,0.263822,0.045434,0.074382,0.046302,0.072824,0.097325,0.159687,0.169336,0.061608,0.132505,0.149590,0.195170,0.289211,0.467360,0.118614,0.333301,0.007824,0.121773,0.028823,0.114538,0.130070,0.262007,0.179569,0.022414,0.284989,0.168877,0.254638
298,6586323,8740225,9530007,12004258,12658442,15058933,1272.598119,1262.360354,1699.597378,1197.558474,2665.807453,2922.868845,3697.020359,2984.153327,3208.145641,4348.370647,4748.384155,7774.778497,5884.910274,6669.14659,0.289211,0.367649,0.208826,0.263822,0.045434,0.074382,0.046302,0.072824,0.097325,0.159687,0.169336,0.061608,0.132505,0.149590,0.195170,0.289211,0.467360,0.118614,0.333301,0.007824,0.121773,0.028823,0.114538,0.130070,0.262007,0.179569,0.022414,0.284989,0.168877,0.254638
272,1288063,32867600,35333463,41016810,62774704,46393709,7654.06445,7712.477862,8003.466801,304.674382,278.72281,293.854287,288.095159,336.846815,366.343288,9466.474654,9925.130056,12722.335608,19161.997558,12686.275362,0.104652,0.104280,0.113009,0.120051,0.126378,0.100744,0.090543,0.077415,0.095218,0.094746,0.117366,0.130947,0.169541,0.183407,0.202870,0.104652,0.103910,0.122469,0.127531,0.133038,0.080310,0.081375,0.066190,0.117115,0.094277,0.145387,0.146100,0.219509,0.198406,0.224398
271,2238589,11362648,11813070,12121768,12137896,13541709,2970.327752,2513.851881,3178.576186,792.845196,806.285973,848.135755,963.455691,881.44,965.741588,4053.745273,5342.862958,4733.216712,5909.394352,5444.997587,0.095502,0.162814,0.183644,0.117736,0.146123,0.133623,0.146421,0.181739,0.151489,0.244251,0.222326,0.118128,0.173446,0.216230,0.239422,0.095502,0.277569,0.207140,0.075482,0.181354,0.122192,0.160445,0.225577,0.126274,0.393813,0.202369,0.062765,0.254670,0.269566,0.265103
261,9483399,10249234,10054187,14018071,14268617,15291984,2195.717094,2231.476618,4466.133241,555.157594,526.042657,420.8505,518.017611,682.906433,2109.766185,2320.406158,2260.383768,7560.987594,3616.886439,3796.421053,0.113698,0.113218,0.114942,0.136998,0.129616,0.147311,0.177928,0.188647,0.198229,0.210650,0.184862,0.104449,0.183642,0.196550,0.202859,0.113698,0.112739,0.116693,0.163286,0.122632,0.167422,0.214908,0.200012,0.208298,0.223849,0.162231,0.059015,0.322877,0.210365,0.209371
194,10851846,13516105,13733686,14366990,14523473,17941640,2835.734293,2891.703548,2708.237443,2325.806461,2440.066738,3038.910731,3181.002618,3350.912005,3601.674743,3975.325,4504.324697,6064.579992,5423.253547,5417.161836,0.161869,0.184134,0.140410,0.094561,0.099221,0.123527,0.082906,0.077635,0.111731,0.152333,0.161712,0.162409,0.148777,0.148654,0.113555,0.161869,0.209462,0.107069,0.063683,0.104111,0.153786,0.055643,0.072700,0.160801,0.207690,0.171668,0.163109,0.136289,0.148531,0.086743
150,4608395,6376138,6992985,6727557,6624627,7409741,4394.58683,4554.539535,3196.206117,1643.872418,2367.203641,1980.358385,2124.391231,1837.625488,2068.39991,2852.858166,3165.67904,3563.324682,3461.142633,4648.520075,0.056096,0.054211,0.082838,0.086063,0.086013,0.067333,0.058307,0.074712,0.085962,0.088739,0.104563,0.060162,0.088098,0.078428,0.073902,0.056096,0.052389,0.126582,0.089414,0.085962,0.052711,0.050490,0.095734,0.098906,0.091606,0.123208,0.034615,0.129005,0.069819,0.069638
136,7836705,13540428,14901170,15607116,31016994,17664815,657.914363,828.468699,899.173699,1248.926579,1122.231493,980.895326,1202.376611,1119.956394,1288.296071,2448.540325,2820.588681,3070.453669,5494.595926,2690.346482,0.096881,0.143518,0.177774,0.105182,0.085153,0.089867,0.088557,0.109239,0.114524,0.128238,0.194682,0.253140,0.302704,0.230962,0.259768,0.096881,0.212603,0.220206,0.062233,0.068939,0.094842,0.087265,0.134751,0.120065,0.143595,0.295551,0.329153,0.361973,0.176223,0.292167
92,12635476,12225380,14335319,15328548,15729385,17349161,1375.212457,1403.892617,3178.229235,2531.262568,2735.060804,2051.478632,2352.008333,2827.116078,3266.66908,3181.20739,3765.515892,5025.753443,5184.372116,4906.436934,0.012796,0.039827,0.060112,0.093611,0.071001,0.034212,0.029691,0.023534,0.019908,0.018628,0.017431,0.013893,0.017028,0.024832,0.038174,0.012796,0.123958,0.090729,0.145778,0.053852,0.016485,0.025767,0.018654,0.016841,0.017429,0.016311,0.011073,0.020870,0.036213,0.058684
91,12635476,12225380,14335319,15328548,15729385,17349161,1375.212457,1403.892617,3178.229235,2531.262568,2735.060804,2051.478632,2352.008333,2827.116078,3266.66908,3181.20739,3765.515892,5025.753443,5184.372116,4906.436934,0.012796,0.039827,0.060112,0.093611,0.071001,0.034212,0.029691,0.023534,0.019908,0.018628,0.017431,0.013893,0.017028,0.024832,0.038174,0.012796,0.123958,0.090729,0.145778,0.053852,0.016485,0.025767,0.018654,0.016841,0.017429,0.016311,0.011073,0.020870,0.036213,0.058684
84,13763737,15093005,19313798,19440623,20557392,24089917,6445.042538,6533.801834,6771.640865,6588.566532,6853.556382,6829.419524,6942.0058,7107.107037,7616.899281,7914.528055,9486.14833,14242.214652,10751.774059,10308.051776,0.129419,0.138732,0.143194,0.141381,0.110389,0.084107,0.075778,0.101775,0.061863,0.051004,0.073908,0.017461,0.059754,0.061646,0.078615,0.129419,0.148716,0.147799,0.139591,0.086191,0.064082,0.068273,0.136691,0.037603,0.042052,0.107095,0.004125,0.204483,0.063599,0.100255
77,3608512,3735118,4043991,4135613,4138087,6688364,901.185659,1101.352336,1329.967428,1575.810965,1561.515563,2281.880516,2327.939352,2264.165468,2198.971359,1725.227714,2518.051681,1784.899871,1436.835764,2368.40085,0.211049,0.257929,0.253324,0.206658,0.203789,0.333782,0.302957,0.318031,0.330796,0.310275,0.269483,0.354735,0.344776,0.325564,0.362141,0.211049,0.315222,0.248801,0.168588,0.200959,0.546695,0.274978,0.333856,0.344073,0.291026,0.234054,0.466957,0.335096,0.307423,0.402827
76,21355068,25584408,27951569,28599693,39380509,35085070,2439.337662,2467.521681,2952.705177,2252.986715,3094.193277,4038.216522,4804.620082,4830.874551,5313.527743,6372.206227,6698.195303,16067.243258,7532.614575,5571.711926,0.151533,0.169507,0.188451,0.199859,0.218215,0.214221,0.211171,0.226854,0.249659,0.318411,0.314514,0.166177,0.418522,0.313715,0.297885,0.151533,0.189614,0.209511,0.211958,0.238257,0.210300,0.208164,0.243701,0.274758,0.406096,0.310665,0.087801,1.054061,0.235154,0.282854
70,15341984,33751218,35598858,36383406,37499176,40128936,4653.801446,4693.740777,5256.780104,3298.644996,3278.287208,3007.98983,2727.577225,2812.004918,2650.653766,5885.129555,6318.576145,8457.32357,8353.57006,8492.896508,0.066332,0.080789,0.117466,0.077732,0.080841,0.095288,0.096481,0.112554,0.117598,0.154512,0.140041,0.147228,0.160104,0.149831,0.144647,0.066332,0.098396,0.170795,0.051439,0.084075,0.112316,0.097688,0.131305,0.122869,0.203013,0.126925,0.154783,0.174106,0.140218,0.139642
42,9729143,9935694,10329851,14208612,31709290,18032607,2034.179581,2164.538796,1959.210082,2409.951007,2436.662517,2786.182636,3111.994606,3345.052862,3173.236464,3459.503482,3523.141542,9478.727151,10587.409015,5715.564818,0.159475,0.162946,0.133107,0.167266,0.159762,0.183950,0.153748,0.183016,0.138353,0.113436,0.103863,0.091891,0.139019,0.094926,0.109508,0.159475,0.166493,0.108732,0.210192,0.152595,0.211801,0.128504,0.217857,0.104590,0.093007,0.095098,0.081299,0.210317,0.064819,0.126329
41,6780538,10383512,11011967,11033509,18737239,11924863,2092.394346,1995.246825,2430.519608,2704.329665,2824.37695,3104.418668,2659.802619,2915.344794,3158.145319,4604.661641,4394.240623,3735.107989,5935.14064,5023.109941,0.322542,0.244286,0.235360,0.168672,0.139043,0.198687,0.246955,0.204446,0.186933,0.208886,0.251836,0.376052,0.383121,0.297004,0.278988,0.322542,0.185016,0.226760,0.120880,0.114618,0.283916,0.306949,0.169255,0.170920,0.233417,0.303617,0.561537,0.390323,0.230244,0.262064
39,13642862,17036008,18595353,18960056,44872881,27254224,4013.018598,4299.047458,4544.170873,4262.726525,3857.700911,4230.932187,3388.73937,3515.903932,3310.570735,3754.078449,4159.10378,4148.808753,10175.256463,6421.824694,0.089020,0.136123,0.083324,0.103560,0.090817,0.129420,0.113873,0.114967,0.118489,0.102997,0.104498,0.135849,0.169085,0.125519,0.136633,0.089020,0.208148,0.051005,0.128711,0.079643,0.184430,0.100193,0.116072,0.122119,0.089530,0.106022,0.176606,0.210452,0.093177,0.148732
38,9500581,13604830,15423586,15890396,15909151,20429152,4722.42641,4985.535731,5550.98634,3469.444351,3519.503505,4588.982236,4285.572239,4573.599176,4714.928536,6708.496055,7254.74412,12223.381538,9555.045646,7359.204611,0.066803,0.097360,0.070351,0.068887,0.089876,0.054274,0.080643,0.092724,0.116730,0.122589,0.107790,0.113189,0.099639,0.119128,0.142896,0.066803,0.141894,0.050835,0.067453,0.117261,0.032775,0.119822,0.106615,0.146950,0.128742,0.094778,0.118858,0.087712,0.142428,0.171406
31,35209137,41760038,42588063,45243794,46204617,59600165,3457.785019,2824.330658,3538.794768,3164.257902,3770.051997,6243.517032,7420.34582,8403.919834,8498.464156,10604.377349,10716.674132,14848.636035,14790.210307,18226.350153,0.183640,0.189530,0.172397,0.170754,0.130424,0.120703,0.106721,0.121214,0.136086,0.141924,0.162684,0.139130,0.158499,0.139632,0.126125,0.183640,0.195609,0.156812,0.169126,0.099619,0.111706,0.094358,0.137676,0.152782,0.148013,0.186480,0.118986,0.180565,0.123011,0.113924
30,35209137,41760038,42588063,45243794,46204617,59600165,3457.785019,2824.330658,3538.794768,3164.257902,3770.051997,6243.517032,7420.34582,8403.919834,8498.464156,10604.377349,10716.674132,14848.636035,14790.210307,18226.350153,0.182396,0.187928,0.172397,0.170754,0.130424,0.120703,0.106721,0.121214,0.136086,0.141924,0.162684,0.139130,0.158499,0.139632,0.126125,0.182396,0.193627,0.158149,0.169126,0.099619,0.111706,0.094358,0.137676,0.152782,0.148013,0.186480,0.118986,0.180565,0.123011,0.113924
28,7449994,8013120,8843051,9778026,9848455,10825621,2323.310467,2357.30546,2305.664637,2501.079231,2617.034884,3203.346048,3627.165521,3381.981436,4129.708426,4345.509761,4516.369254,4225.594641,4700.933174,4712.939051,0.073192,0.087801,0.085663,0.093306,0.108708,0.054933,0.055576,0.050342,0.083526,0.135581,0.147812,0.168836,0.176339,0.216219,0.181019,0.073192,0.105325,0.083577,0.101630,0.126653,0.027759,0.056227,0.045601,0.138585,0.220078,0.161147,0.192851,0.184175,0.265117,0.151550
13,1358239,47515340,50009087,52776589,57878099,63855086,2492.481157,2543.982501,2681.513653,362.01197,359.678512,263.017585,209.935694,163.982135,112.139944,4242.819895,4255.730321,10182.633417,4329.600464,4513.045869,0.092509,0.089082,0.087855,0.088710,0.091266,0.087862,0.089072,0.191683,0.229840,0.166798,0.220379,0.151311,0.270468,0.250223,0.359084,0.092509,0.085781,0.086646,0.089572,0.093895,0.084586,0.090299,0.412501,0.275594,0.121048,0.291172,0.103890,0.483458,0.231494,0.515306

In [80]:
policy_data = pd.read_csv("PolicyMaster.csv", low_memory=False)

In [81]:
policy_data

,CoC Number,Housing First - 2024,Rental Assistance - 2024,Hostile Policies - 2024,\nCity-Provided \nShelter - 2024,Housing First - 2023,Rental Assistance - 2023,Hostile Policies - 2023,\nCity-Provided \nShelter - 2023,Housing First - 2022,Rental Assistance - 2022,Hostile Policies - 2022,\nCity-Provided \nShelter - 2022,Housing First - 2021,Rental Assistance - 2021,Hostile Policies - 2021,\nCity-Provided \nShelter - 2021,Housing First - 2020,Rental Assistance - 2020,Hostile Policies - 2020,\nCity-Provided \nShelter - 2020,Housing First - 2019,Rental Assistance - 2019,Hostile Policies - 2019,\nCity-Provided \nShelter - 2019,Housing First - 2018,Rental Assistance - 2018,Hostile Policies - 2018,\nCity-Provided \nShelter - 2018,Housing First - 2017,Rental Assistance - 2017,Hostile Policies - 2017,\nCity-Provided \nShelter - 2017,Housing First - 2016,Rental Assistance - 2016,Hostile Policies - 2016,\nCity-Provided \nShelter - 2016,Housing First - 2015,Rental Assistance - 2015,Hostile Policies - 2015,\nCity-Provided \nShelter - 2015,Housing First - 2014,Rental Assistance - 2014,Hostile Policies - 2014,\nCity-Provided \nShelter - 2014,Housing First - 2013,Rental Assistance - 2013,Hostile Policies - 2013,\nCity-Provided \nShelter - 2013,Housing First - 2012,Rental Assistance - 2012,Hostile Policies - 2012,\nCity-Provided \nShelter - 2012,Housing First - 2011,Rental Assistance - 2011,Hostile Policies - 2011,\nCity-Provided \nShelter - 2011,Housing First - 2010,Rental Assistance - 2010,Hostile Policies - 2010,\nCity-Provided \nShelter - 2010
0,AZ-502,1,1,0,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,0,1,1,1,1,1,1,1,0,1,1,1,0,1,1,1,0,1,1,1,0,1,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,CA-500,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,1,1,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0
2,CA-501,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,0,0,1,1,0,0,1,1,0,1,1,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,CA-502,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,1,0,0,1,1,0,0,1,1,0,1,1,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,CA-503,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5,CA-504,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,0,1,0,0,1,1,0,1,1,1,0,0,1,1,0,0,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
6,CA-505,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
7,CA-506,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
8,CA-511,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
9,CA-514,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10,CA-516,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
11,CA-600,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
12,CA-601,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1,0,0,1,1,0,0,1,1,0,1,1,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
13,CA-602,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
14,CA-604,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,0,0,0,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
15,CA-606,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,0,0,0,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
16,CA-608,1,0,1,0,1,1,1,1,1,1,1,1,1,0,1,1,1,0,0,0,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0
17,CA-609,1,0,1,0,1,1,1,1,1,1,1,1,1,0,1,1,1,0,0,0,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
18,CA-611,1,0,1,0,1,1,1,1,1,1,1,1,1,0,1,1,1,0,0,0,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
19,CO-503,0,0,0,1,0,0,1,1,1,1,1,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
20,DC-500,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
21,FL-507,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
22,FL-600,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
23,FL-601,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0
24,GA-500,1,0,1,0,1,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
25,HI-501,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
26,IL-510,1,0,1,0,1,0,1,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0
27,MA-500,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
28,MA-504,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
29,ME-500,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
30,MN-500,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
31,NJ-504,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
32,NM-500,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
33,NV-500,0,0,1,1,1,0,1,1,1,0,1,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
34,NY-600,0,1,0,1,0,1,0,1,0,1,1,1,0,1,0,1,0,1,1,1,0,1,1,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1
35,NY-603,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
36,OH-503,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
37,OR-500,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
38,OR-501,0,0,1,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
39,PA-500,0,0,1,1,0,0,0,0,0,0,0,0,0,0,1,1,0,1,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
40,PA-509,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
41,RI-500,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
42,TX-500,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
43,TX-503,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
44,TX-600,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
45,TX-601,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
46,TX-700,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
47,UT-500,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
48,WA-500,0,0,1,1,0,0,1,1,0,0,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
49,WA-503,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0